import java.awt.*;
import javax.swing.*;

/**
 *      File Name:  
 *  Programmed By:  Joseph Calarco
 * Programmed For:  
 *           Date:   
 *    Description:   
 */

public class TicTac extends javax.swing.JFrame {
    TicTacEvent tictac = new TicTacEvent(this);     //Joins the two programs (TicTac.java and TicTacEvent.java) to work with each other
    JPanel row1 = new JPanel();                     //Creates a new frame
    JButton[][] boxes = new JButton [3][3];         //Creates a 2D gride of arrays for the 9 buttons
    JOptionPane win = new JOptionPane("Winner");    //Pip to declare the winner
    ImageIcon back = new ImageIcon("cardback.jpg"); //Loads the image to be used as the background of buttons
    public TicTac() {
        super("Tic Tac Toe");                           //creates title of app
        setSize(500,600);                               //sets size of the frame
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); //sets the program to quite when window closes
        FlowLayout layout = new FlowLayout();           //arranges components from left to right centering horizontally to a 5p gap
        setLayout(layout);
        int name = 0;                                       //creates variable to keep track of box number
        String newname;                                     //will be used to hold button names
        GridLayout layout1 = new GridLayout(4, 3, 10, 10);  //Arranges the components in a rectangular grid where all cells are equal
        row1.setLayout(layout1);
        for(int x=0;x<=2;x++){                              //Creates and adds the buttons to the GridLayout goes up and down
            for(int y=0;y<=2;y++){                          //goes across the GridLayout
                name += 1;                                  //Adds one to the loop
                newname = Integer.toString(name);           //names newname from number 1-9
                boxes[x][y] = new JButton(newname);         // sets the boxes to show number 1-9
                boxes[x][y].setIcon(back);                  //sets the images of the back of the buttons
                row1.add(boxes[x][y]);                      //adds remaining components to the GridLayout
            }
        }
        add(row1);                                     //adds the GridLayout to the FlowLayout
        for(int x=0;x<=2;x++){                          //runs a loop to see which button was pressed
            for(int y=0;y<=2;y++){                      
                boxes[x][y].addActionListener(tictac);  //Listents to button being clicked
            }
        }
        setVisible(true);                               //shows the FlowLayout on the screen
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tic Tac Toe");
        setPreferredSize(new java.awt.Dimension(475, 375));
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
